## Library

In [535]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
import math 

## Dataset

In [536]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=55, n_features=2, n_informative=2,
                           n_redundant=0, n_classes=2, random_state=42)

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (55, 2)
Shape of y: (55,)


In [537]:
X

array([[-0.40933759, -1.92807208],
       [ 1.50033205, -0.46741109],
       [-1.83205466,  0.0132159 ],
       [-1.50410704, -0.77392333],
       [-1.62147856,  0.23159609],
       [ 0.35681306, -1.63768603],
       [ 1.87477825,  0.74638576],
       [-0.57013259,  1.43231976],
       [-1.22384206,  0.69776168],
       [-0.74891786, -1.38431951],
       [-1.53419812,  0.67228532],
       [ 1.01568877,  0.1128579 ],
       [ 2.30971874, -1.79912523],
       [ 0.14883634, -0.82407129],
       [-1.93849132, -0.62234169],
       [ 1.18034677,  1.18384689],
       [-0.52150238,  2.36558871],
       [-1.42604961, -0.58446926],
       [ 1.04325557,  0.85907783],
       [-0.17002098,  0.87014904],
       [ 0.67776608, -0.88279053],
       [ 1.08684338,  1.27590592],
       [ 0.66918828,  0.81109084],
       [ 1.59663763,  1.246863  ],
       [-1.51929788,  0.79604508],
       [ 0.74477569,  1.03297297],
       [-1.43720002, -0.98300724],
       [ 1.2782432 , -0.69116083],
       [-0.80545222,

In [538]:
y

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1])

In [539]:
df = pd.DataFrame(X)
df

0         1
0  -0.409338 -1.928072
1   1.500332 -0.467411
2  -1.832055  0.013216
3  -1.504107 -0.773923
4  -1.621479  0.231596
5   0.356813 -1.637686
6   1.874778  0.746386
7  -0.570133  1.432320
8  -1.223842  0.697762
9  -0.748918 -1.384320
10 -1.534198  0.672285
11  1.015689  0.112858
12  2.309719 -1.799125
13  0.148836 -0.824071
14 -1.938491 -0.622342
15  1.180347  1.183847
16 -0.521502  2.365589
17 -1.426050 -0.584469
18  1.043256  0.859078
19 -0.170021  0.870149
20  0.677766 -0.882791
21  1.086843  1.275906
22  0.669188  0.811091
23  1.596638  1.246863
24 -1.519298  0.796045
25  0.744776  1.032973
26 -1.437200 -0.983007
27  1.278243 -0.691161
28 -0.805452  1.554764
29 -1.239589  0.050051
30 -0.539831 -1.191524
31  4.021132 -0.268330
32 -0.143034  1.763283
33  1.884013 -1.490837
34  1.507002  0.794957
35 -0.574672  1.630260
36  1.871900  0.498238
37  1.499406 -1.654791
38 -0.705226 -0.005346
39 -1.016215  1.105503
40 -0.929703 -0.466127
41  0.768514  1.120913
42 -1.225967  1.006834
43 -1.215279 -0.790514
44 -0.765682 -0.358167
45 -2.592273  0.080238
46 -0.385318  2.231255
47 -1.280225  0.316931
48 -2.066615 -0.578225
49  0.464147  1.421116
50  0.456382 -2.089603
51  1.378543 -2.066144
52  1.931669 -1.961119
53  1.488649 -1.088761
54 -0.335187  1.567241

In [540]:
output = y
output

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1])

In [541]:
# number of features or columns
n = len(df.columns)
total_number = len(df) 
print(n,total_number)

2 55


## Generating n number of random weights ,  a fixed threshold value and a fixed learning rate

In [542]:
n

2

In [543]:
np.random.seed(42)
weights = np.random.rand(n)
weights

array([0.37454012, 0.95071431])

In [544]:
threshold = 0.5
threshold

0.5

In [545]:
learning_rate = 0.4
learning_rate

0.4

## Train Test

In [546]:
train_percentage = 80
test_percentage = 100 - train_percentage

print('Train Percentage :',train_percentage)
print('Test Percentage :',test_percentage)

Train Percentage : 80
Test Percentage : 20


In [547]:
import math

no_of_train_data = math.ceil(( total_number * train_percentage ) / 100)
no_of_test_data = total_number - no_of_train_data

print('No of Train Data :',no_of_train_data)
print('No of Test Data :',no_of_test_data)

No of Train Data : 44
No of Test Data : 11


## Adjusting Weights

In [548]:
total_number

55

In [549]:
# df.columns
# df.columns[0]
# df[df.columns[0]]
df[df.columns[0]]

0    -0.409338
1     1.500332
2    -1.832055
3    -1.504107
4    -1.621479
5     0.356813
6     1.874778
7    -0.570133
8    -1.223842
9    -0.748918
10   -1.534198
11    1.015689
12    2.309719
13    0.148836
14   -1.938491
15    1.180347
16   -0.521502
17   -1.426050
18    1.043256
19   -0.170021
20    0.677766
21    1.086843
22    0.669188
23    1.596638
24   -1.519298
25    0.744776
26   -1.437200
27    1.278243
28   -0.805452
29   -1.239589
30   -0.539831
31    4.021132
32   -0.143034
33    1.884013
34    1.507002
35   -0.574672
36    1.871900
37    1.499406
38   -0.705226
39   -1.016215
40   -0.929703
41    0.768514
42   -1.225967
43   -1.215279
44   -0.765682
45   -2.592273
46   -0.385318
47   -1.280225
48   -2.066615
49    0.464147
50    0.456382
51    1.378543
52    1.931669
53    1.488649
54   -0.335187
Name: 0, dtype: float64

In [550]:
counter = 0

while counter!=no_of_train_data :

    for i in range(no_of_train_data):
        summation = 0
        
        for j in range(n):
            summation = summation + df[df.columns[j]][i] * weights[j]
        
        if summation >= threshold :
            predicted_output = 1

        else:
            predicted_output = 0

        if predicted_output == output[i]:
            counter = counter + 1
        
        else:
            difference = output[i] - predicted_output
            for j in range(n):
                weights[j] = weights[j] + learning_rate * difference * df[df.columns[j]][i]
            counter = 0
            break

KeyboardInterrupt: 

In [ ]:
weights

array([-0.22420138,  4.55566437])

In [ ]:
# proof that these weights are valid for train data

for i in range(no_of_train_data) :
    summation = 0

    for j in range(n):
        summation = summation + df[df.columns[j]][i] * weights[j]

    if summation >= threshold :
        predicted_output = 1
    else:
        predicted_output = 0
    
    print(predicted_output)

0
0
0
0
1
0
1
1
1
0
1
0
0
0
0
1
1
0
1
1
0
1
1
1
1
1
0
0
1
1
0
0
1


In [ ]:
right = 0
wrong = 0

for i in range(no_of_train_data,total_number) :
    summation = 0

    for j in range(n):
        summation = summation + df[df.columns[j]][i] * weights[j]

    if summation >= threshold :
        predicted_output = 1

    else:
        predicted_output = 0
    
    if predicted_output == output[i]:
        right = right + 1

    else:
        wrong = wrong + 1

accuracy = ( right * 100 ) / no_of_test_data

print('No of Test Data :',no_of_test_data)
print('Right :',right)
print('Wrong :',wrong)
print('Accuracy :',accuracy)

No of Test Data : 22
Right : 20
Wrong : 2
Accuracy : 90.9090909090909
