## Generating n bit of data

In [39]:
n = int(input('Enter Number of bits : '))
count = 0
i = n
string = 'bit_'
total_number = 2 ** n

In [40]:
value = list()
dictionary = dict()

while i >= 1 :
    key = string + str(i)
    d = 2 ** count

    while len(value) != total_number:
        for j in range(d):
            value.append(0)
        for j in range(d):
            value.append(1)
    
    dictionary[key] = value
    value = list()
    count = count + 1
    i = i - 1

In [41]:
dictionary 

{'bit_3': [0, 1, 0, 1, 0, 1, 0, 1],
 'bit_2': [0, 0, 1, 1, 0, 0, 1, 1],
 'bit_1': [0, 0, 0, 0, 1, 1, 1, 1]}

In [42]:
list(dictionary.items())

[('bit_3', [0, 1, 0, 1, 0, 1, 0, 1]),
 ('bit_2', [0, 0, 1, 1, 0, 0, 1, 1]),
 ('bit_1', [0, 0, 0, 0, 1, 1, 1, 1])]

In [43]:
l = list(dictionary.items())
l

[('bit_3', [0, 1, 0, 1, 0, 1, 0, 1]),
 ('bit_2', [0, 0, 1, 1, 0, 0, 1, 1]),
 ('bit_1', [0, 0, 0, 0, 1, 1, 1, 1])]

In [44]:
reversed_dictionary = dict()
i = n-1
while i >= 0:
    reversed_dictionary[l[i][0]] = l[i][1]
    i = i - 1
reversed_dictionary

{'bit_1': [0, 0, 0, 0, 1, 1, 1, 1],
 'bit_2': [0, 0, 1, 1, 0, 0, 1, 1],
 'bit_3': [0, 1, 0, 1, 0, 1, 0, 1]}

In [45]:
dictionary = reversed_dictionary
dictionary

{'bit_1': [0, 0, 0, 0, 1, 1, 1, 1],
 'bit_2': [0, 0, 1, 1, 0, 0, 1, 1],
 'bit_3': [0, 1, 0, 1, 0, 1, 0, 1]}

In [46]:
output = dictionary['bit_1']
output

[0, 0, 0, 0, 1, 1, 1, 1]

In [47]:
import pandas as pd

df = pd.DataFrame(data=dictionary)
df

bit_1  bit_2  bit_3
0      0      0      0
1      0      0      1
2      0      1      0
3      0      1      1
4      1      0      0
5      1      0      1
6      1      1      0
7      1      1      1

In [48]:
df['Output'] = output
df

bit_1  bit_2  bit_3  Output
0      0      0      0       0
1      0      0      1       0
2      0      1      0       0
3      0      1      1       0
4      1      0      0       1
5      1      0      1       1
6      1      1      0       1
7      1      1      1       1

In [49]:
df = df.drop('Output',axis=1)
df

bit_1  bit_2  bit_3
0      0      0      0
1      0      0      1
2      0      1      0
3      0      1      1
4      1      0      0
5      1      0      1
6      1      1      0
7      1      1      1

In [50]:
df.iloc[0,0]

0

In [51]:
df.shape

(8, 3)

In [52]:
n = df.shape[0]
m = df.shape[1]

print('number of rows :',n)
print('number of features :',m)

number of rows : 8
number of features : 3


## Initializing weight with random number

In [53]:
import numpy as np

np.random.seed(113)
w = np.random.rand(n,m)
print(w)

[[0.85198549 0.0739036  0.89493176]
 [0.43649355 0.12767773 0.57585787]
 [0.84047092 0.43512055 0.69591056]
 [0.6846381  0.70064837 0.77969426]
 [0.64274937 0.96102617 0.10846489]
 [0.79610634 0.83258008 0.26600836]
 [0.83668539 0.53212691 0.51690756]
 [0.09858771 0.91886899 0.66665849]]


In [54]:
w.shape

(8, 3)

In [55]:
w[0,0]

0.8519854927300882

## Initializing distance with 0

In [56]:
closest_node = np.zeros(n,dtype='int')
closest_node

array([0, 0, 0, 0, 0, 0, 0, 0])

## Adjusting weight

In [57]:
d_list = list()
learning_rate = 0.5
distance = 0
neighbor_int = 4
neighbor_float = 4

while neighbor_int != 1:

    # calculating distance from input node to every output nodes
    for i in range(n):
        for j in range(n):
            for k in range(m):
                distance = distance + ((df.iloc[i,k]-w[j,k]) ** 2)
            d_list.append((j,distance))
            distance = 0

        # sorting the distances in ascending order
        for ii in range(len(d_list)):
            for jj in range(ii+1,len(d_list)):
                if d_list[jj][1] < d_list[ii][1]:
                    temp = d_list[ii]
                    d_list[ii] = d_list[jj]
                    d_list[jj] = temp

        # saving the closest node
        closest_node[i] = d_list[0][0]

        # updating weights of closest node and it's neighbor nodes
        for ii in range(neighbor_int):
            node = d_list[ii][0]
            for k in range(m):
                w[node][k] = w[node][k] + learning_rate * (df.iloc[i,k] - w[node][k])
        
        d_list = list()

    neighbor_float = neighbor_float - learning_rate * neighbor_float
    neighbor_int = int(np.ceil(neighbor_float))

In [58]:
closest_node

array([1, 1, 4, 7, 0, 0, 5, 6])