In [111]:
import numpy as np

np.random.seed(42)  # Set the random seed for reproducibility

num_rows = 30
num_cols = 20

random_array = np.random.randint(2, size=(num_rows, num_cols))

print(random_array)

[[0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 0 0]
 [0 0 1 1 1 1 1 0 1 1 0 1 0 1 0 1 1 0 0 0]
 [0 0 0 0 0 1 1 0 1 1 1 1 0 1 0 1 1 1 0 1]
 [0 1 0 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1 1 0]
 [1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 0 1 1 1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1]
 [0 0 1 1 1 0 1 0 0 1 1 0 0 1 1 1 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 0 0]
 [0 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 1]
 [1 0 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 1 0]
 [0 1 0 0 0 1 1 1 0 0 1 1 1 1 0 1 0 1 0 1]
 [1 1 1 0 1 0 0 0 0 1 0 0 0 1 1 1 1 0 0 1]
 [0 0 0 1 1 0 1 1 1 1 1 0 1 0 0 1 0 0 0 1]
 [1 0 1 1 1 1 0 0 1 1 0 0 1 0 1 1 0 0 1 1]
 [0 1 0 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0]
 [1 0 0 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 1 0]
 [1 1 1 0 0 1 0 0 0 0 0 0 1 1 0 1 1 1 1 0]
 [1 1 0 0 1 1 1 1 1 1 0 1 1 0 0 0 0 1 1 1]
 [1 1 1 0 1 0 0 1 0 1 0 1 0 1 1 1 1 1 0 0]
 [0 1 0 1 1 0 0 1 0 1 1 1 1 1 0 0 1 1 0 0]
 [1 0 1 0 1

In [112]:
import pandas as pd
df = pd.DataFrame(data=random_array)
df

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  \
0    0   1   0   0   0   1   0   0   0   1   0   0   0   0   1   0   1   1   
1    1   0   1   1   1   1   1   1   1   1   0   0   1   1   1   0   1   0   
2    0   0   1   1   1   1   1   0   1   1   0   1   0   1   0   1   1   0   
3    0   0   0   0   0   1   1   0   1   1   1   1   0   1   0   1   1   1   
4    0   1   0   1   0   0   1   0   1   1   1   1   1   1   1   1   1   1   
5    0   1   1   1   1   1   1   1   1   0   1   0   1   1   0   1   0   1   
6    1   0   1   0   0   1   1   0   1   1   1   0   0   0   0   0   0   0   
7    1   0   1   1   1   0   0   0   0   1   0   0   0   0   0   1   0   1   
8    0   0   1   1   1   0   1   0   0   1   1   0   0   1   1   1   0   0   
9    0   0   1   0   0   0   1   0   0   1   0   0   0   0   0   1   1   1   
10   0   1   0   0   1   0   1   1   1   0   0   0   0   0   0   0   1   0   
11   0   0   1   1   1   1   0   1   0   0   1   1   1   1   1   1   1   1   
12   1   0   1   0   0   1   0   0   0   0   1   0   1   0   0   0   0   1   
13   0   1   0   0   0   1   1   1   0   0   1   1   1   1   0   1   0   1   
14   1   1   1   0   1   0   0   0   0   1   0   0   0   1   1   1   1   0   
15   0   0   0   1   1   0   1   1   1   1   1   0   1   0   0   1   0   0   
16   1   0   1   1   1   1   0   0   1   1   0   0   1   0   1   1   0   0   
17   0   1   0   1   0   0   0   1   1   0   1   0   0   1   1   0   1   1   
18   1   0   0   1   0   0   1   1   0   0   1   1   1   1   0   1   1   0   
19   1   1   1   0   0   1   0   0   0   0   0   0   1   1   0   1   1   1   
20   1   1   0   0   1   1   1   1   1   1   0   1   1   0   0   0   0   1   
21   1   1   1   0   1   0   0   1   0   1   0   1   0   1   1   1   1   1   
22   0   1   0   1   1   0   0   1   0   1   1   1   1   1   0   0   1   1   
23   1   0   1   0   1   0   1   0   0   1   0   1   0   1   0   1   0   1   
24   1   1   0   1   0   1   0   1   0   0   1   0   0   1   0   0   0   1   
25   0   0   0   1   0   0   1   0   1   1   0   1   0   1   1   0   1   1   
26   1   0   1   0   1   0   0   1   1   1   0   1   0   0   0   1   1   0   
27   0   1   0   1   0   1   0   1   1   0   0   1   0   1   0   1   1   1   
28   1   0   0   0   1   1   1   1   0   0   1   0   0   1   0   1   0   1   
29   1   0   1   1   1   0   1   0   1   0   0   1   0   1   1   1   0   0   

    18  19  
0    1   0  
1    0   0  
2    0   0  
3    0   1  
4    1   0  
5    1   0  
6    0   0  
7    0   1  
8    0   0  
9    0   0  
10   1   0  
11   0   1  
12   1   0  
13   0   1  
14   0   1  
15   0   1  
16   1   1  
17   0   0  
18   1   0  
19   1   0  
20   1   1  
21   0   0  
22   0   0  
23   0   1  
24   0   1  
25   1   1  
26   0   1  
27   1   1  
28   1   1  
29   1   1

In [113]:
df.iloc[0,1]

1

In [114]:
a = list()
a

[]

In [115]:
# fitness function
p = 19
sum = 0
fitness_list = list()
for i in range(30):
    for j in range(20):
        sum = sum + df.iloc[i,j] * (2 ** p)
        p = p - 1
    fitness_list.append(sum)
    sum = 0
    p = 19
fitness_list

[279598,
 785640,
 257368,
 28509,
 339966,
 522966,
 683520,
 754709,
 239216,
 140316,
 309258,
 250877,
 672390,
 291797,
 951417,
 114321,
 773299,
 334444,
 603098,
 934110,
 851335,
 955772,
 366540,
 697685,
 873029,
 77167,
 695577,
 350559,
 586327,
 764275]

In [116]:
df['fitness'] = fitness_list
df

0  1  2  3  4  5  6  7  8  9  ...  11  12  13  14  15  16  17  18  19  \
0   0  1  0  0  0  1  0  0  0  1  ...   0   0   0   1   0   1   1   1   0   
1   1  0  1  1  1  1  1  1  1  1  ...   0   1   1   1   0   1   0   0   0   
2   0  0  1  1  1  1  1  0  1  1  ...   1   0   1   0   1   1   0   0   0   
3   0  0  0  0  0  1  1  0  1  1  ...   1   0   1   0   1   1   1   0   1   
4   0  1  0  1  0  0  1  0  1  1  ...   1   1   1   1   1   1   1   1   0   
5   0  1  1  1  1  1  1  1  1  0  ...   0   1   1   0   1   0   1   1   0   
6   1  0  1  0  0  1  1  0  1  1  ...   0   0   0   0   0   0   0   0   0   
7   1  0  1  1  1  0  0  0  0  1  ...   0   0   0   0   1   0   1   0   1   
8   0  0  1  1  1  0  1  0  0  1  ...   0   0   1   1   1   0   0   0   0   
9   0  0  1  0  0  0  1  0  0  1  ...   0   0   0   0   1   1   1   0   0   
10  0  1  0  0  1  0  1  1  1  0  ...   0   0   0   0   0   1   0   1   0   
11  0  0  1  1  1  1  0  1  0  0  ...   1   1   1   1   1   1   1   0   1   
12  1  0  1  0  0  1  0  0  0  0  ...   0   1   0   0   0   0   1   1   0   
13  0  1  0  0  0  1  1  1  0  0  ...   1   1   1   0   1   0   1   0   1   
14  1  1  1  0  1  0  0  0  0  1  ...   0   0   1   1   1   1   0   0   1   
15  0  0  0  1  1  0  1  1  1  1  ...   0   1   0   0   1   0   0   0   1   
16  1  0  1  1  1  1  0  0  1  1  ...   0   1   0   1   1   0   0   1   1   
17  0  1  0  1  0  0  0  1  1  0  ...   0   0   1   1   0   1   1   0   0   
18  1  0  0  1  0  0  1  1  0  0  ...   1   1   1   0   1   1   0   1   0   
19  1  1  1  0  0  1  0  0  0  0  ...   0   1   1   0   1   1   1   1   0   
20  1  1  0  0  1  1  1  1  1  1  ...   1   1   0   0   0   0   1   1   1   
21  1  1  1  0  1  0  0  1  0  1  ...   1   0   1   1   1   1   1   0   0   
22  0  1  0  1  1  0  0  1  0  1  ...   1   1   1   0   0   1   1   0   0   
23  1  0  1  0  1  0  1  0  0  1  ...   1   0   1   0   1   0   1   0   1   
24  1  1  0  1  0  1  0  1  0  0  ...   0   0   1   0   0   0   1   0   1   
25  0  0  0  1  0  0  1  0  1  1  ...   1   0   1   1   0   1   1   1   1   
26  1  0  1  0  1  0  0  1  1  1  ...   1   0   0   0   1   1   0   0   1   
27  0  1  0  1  0  1  0  1  1  0  ...   1   0   1   0   1   1   1   1   1   
28  1  0  0  0  1  1  1  1  0  0  ...   0   0   1   0   1   0   1   1   1   
29  1  0  1  1  1  0  1  0  1  0  ...   1   0   1   1   1   0   0   1   1   

    fitness  
0    279598  
1    785640  
2    257368  
3     28509  
4    339966  
5    522966  
6    683520  
7    754709  
8    239216  
9    140316  
10   309258  
11   250877  
12   672390  
13   291797  
14   951417  
15   114321  
16   773299  
17   334444  
18   603098  
19   934110  
20   851335  
21   955772  
22   366540  
23   697685  
24   873029  
25    77167  
26   695577  
27   350559  
28   586327  
29   764275  

[30 rows x 21 columns]

In [117]:
df = df.sort_values(by='fitness', ascending=True)

In [118]:
df

0  1  2  3  4  5  6  7  8  9  ...  11  12  13  14  15  16  17  18  19  \
3   0  0  0  0  0  1  1  0  1  1  ...   1   0   1   0   1   1   1   0   1   
25  0  0  0  1  0  0  1  0  1  1  ...   1   0   1   1   0   1   1   1   1   
15  0  0  0  1  1  0  1  1  1  1  ...   0   1   0   0   1   0   0   0   1   
9   0  0  1  0  0  0  1  0  0  1  ...   0   0   0   0   1   1   1   0   0   
8   0  0  1  1  1  0  1  0  0  1  ...   0   0   1   1   1   0   0   0   0   
11  0  0  1  1  1  1  0  1  0  0  ...   1   1   1   1   1   1   1   0   1   
2   0  0  1  1  1  1  1  0  1  1  ...   1   0   1   0   1   1   0   0   0   
0   0  1  0  0  0  1  0  0  0  1  ...   0   0   0   1   0   1   1   1   0   
13  0  1  0  0  0  1  1  1  0  0  ...   1   1   1   0   1   0   1   0   1   
10  0  1  0  0  1  0  1  1  1  0  ...   0   0   0   0   0   1   0   1   0   
17  0  1  0  1  0  0  0  1  1  0  ...   0   0   1   1   0   1   1   0   0   
4   0  1  0  1  0  0  1  0  1  1  ...   1   1   1   1   1   1   1   1   0   
27  0  1  0  1  0  1  0  1  1  0  ...   1   0   1   0   1   1   1   1   1   
22  0  1  0  1  1  0  0  1  0  1  ...   1   1   1   0   0   1   1   0   0   
5   0  1  1  1  1  1  1  1  1  0  ...   0   1   1   0   1   0   1   1   0   
28  1  0  0  0  1  1  1  1  0  0  ...   0   0   1   0   1   0   1   1   1   
18  1  0  0  1  0  0  1  1  0  0  ...   1   1   1   0   1   1   0   1   0   
12  1  0  1  0  0  1  0  0  0  0  ...   0   1   0   0   0   0   1   1   0   
6   1  0  1  0  0  1  1  0  1  1  ...   0   0   0   0   0   0   0   0   0   
26  1  0  1  0  1  0  0  1  1  1  ...   1   0   0   0   1   1   0   0   1   
23  1  0  1  0  1  0  1  0  0  1  ...   1   0   1   0   1   0   1   0   1   
7   1  0  1  1  1  0  0  0  0  1  ...   0   0   0   0   1   0   1   0   1   
29  1  0  1  1  1  0  1  0  1  0  ...   1   0   1   1   1   0   0   1   1   
16  1  0  1  1  1  1  0  0  1  1  ...   0   1   0   1   1   0   0   1   1   
1   1  0  1  1  1  1  1  1  1  1  ...   0   1   1   1   0   1   0   0   0   
20  1  1  0  0  1  1  1  1  1  1  ...   1   1   0   0   0   0   1   1   1   
24  1  1  0  1  0  1  0  1  0  0  ...   0   0   1   0   0   0   1   0   1   
19  1  1  1  0  0  1  0  0  0  0  ...   0   1   1   0   1   1   1   1   0   
14  1  1  1  0  1  0  0  0  0  1  ...   0   0   1   1   1   1   0   0   1   
21  1  1  1  0  1  0  0  1  0  1  ...   1   0   1   1   1   1   1   0   0   

    fitness  
3     28509  
25    77167  
15   114321  
9    140316  
8    239216  
11   250877  
2    257368  
0    279598  
13   291797  
10   309258  
17   334444  
4    339966  
27   350559  
22   366540  
5    522966  
28   586327  
18   603098  
12   672390  
6    683520  
26   695577  
23   697685  
7    754709  
29   764275  
16   773299  
1    785640  
20   851335  
24   873029  
19   934110  
14   951417  
21   955772  

[30 rows x 21 columns]

In [119]:
list(df.iloc[0,:-1])

[0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1]

In [120]:
df['fitness'][0]

279598

In [121]:
df

0  1  2  3  4  5  6  7  8  9  ...  11  12  13  14  15  16  17  18  19  \
3   0  0  0  0  0  1  1  0  1  1  ...   1   0   1   0   1   1   1   0   1   
25  0  0  0  1  0  0  1  0  1  1  ...   1   0   1   1   0   1   1   1   1   
15  0  0  0  1  1  0  1  1  1  1  ...   0   1   0   0   1   0   0   0   1   
9   0  0  1  0  0  0  1  0  0  1  ...   0   0   0   0   1   1   1   0   0   
8   0  0  1  1  1  0  1  0  0  1  ...   0   0   1   1   1   0   0   0   0   
11  0  0  1  1  1  1  0  1  0  0  ...   1   1   1   1   1   1   1   0   1   
2   0  0  1  1  1  1  1  0  1  1  ...   1   0   1   0   1   1   0   0   0   
0   0  1  0  0  0  1  0  0  0  1  ...   0   0   0   1   0   1   1   1   0   
13  0  1  0  0  0  1  1  1  0  0  ...   1   1   1   0   1   0   1   0   1   
10  0  1  0  0  1  0  1  1  1  0  ...   0   0   0   0   0   1   0   1   0   
17  0  1  0  1  0  0  0  1  1  0  ...   0   0   1   1   0   1   1   0   0   
4   0  1  0  1  0  0  1  0  1  1  ...   1   1   1   1   1   1   1   1   0   
27  0  1  0  1  0  1  0  1  1  0  ...   1   0   1   0   1   1   1   1   1   
22  0  1  0  1  1  0  0  1  0  1  ...   1   1   1   0   0   1   1   0   0   
5   0  1  1  1  1  1  1  1  1  0  ...   0   1   1   0   1   0   1   1   0   
28  1  0  0  0  1  1  1  1  0  0  ...   0   0   1   0   1   0   1   1   1   
18  1  0  0  1  0  0  1  1  0  0  ...   1   1   1   0   1   1   0   1   0   
12  1  0  1  0  0  1  0  0  0  0  ...   0   1   0   0   0   0   1   1   0   
6   1  0  1  0  0  1  1  0  1  1  ...   0   0   0   0   0   0   0   0   0   
26  1  0  1  0  1  0  0  1  1  1  ...   1   0   0   0   1   1   0   0   1   
23  1  0  1  0  1  0  1  0  0  1  ...   1   0   1   0   1   0   1   0   1   
7   1  0  1  1  1  0  0  0  0  1  ...   0   0   0   0   1   0   1   0   1   
29  1  0  1  1  1  0  1  0  1  0  ...   1   0   1   1   1   0   0   1   1   
16  1  0  1  1  1  1  0  0  1  1  ...   0   1   0   1   1   0   0   1   1   
1   1  0  1  1  1  1  1  1  1  1  ...   0   1   1   1   0   1   0   0   0   
20  1  1  0  0  1  1  1  1  1  1  ...   1   1   0   0   0   0   1   1   1   
24  1  1  0  1  0  1  0  1  0  0  ...   0   0   1   0   0   0   1   0   1   
19  1  1  1  0  0  1  0  0  0  0  ...   0   1   1   0   1   1   1   1   0   
14  1  1  1  0  1  0  0  0  0  1  ...   0   0   1   1   1   1   0   0   1   
21  1  1  1  0  1  0  0  1  0  1  ...   1   0   1   1   1   1   1   0   0   

    fitness  
3     28509  
25    77167  
15   114321  
9    140316  
8    239216  
11   250877  
2    257368  
0    279598  
13   291797  
10   309258  
17   334444  
4    339966  
27   350559  
22   366540  
5    522966  
28   586327  
18   603098  
12   672390  
6    683520  
26   695577  
23   697685  
7    754709  
29   764275  
16   773299  
1    785640  
20   851335  
24   873029  
19   934110  
14   951417  
21   955772  

[30 rows x 21 columns]

In [122]:
df = df[:15][:]
df

0  1  2  3  4  5  6  7  8  9  ...  11  12  13  14  15  16  17  18  19  \
3   0  0  0  0  0  1  1  0  1  1  ...   1   0   1   0   1   1   1   0   1   
25  0  0  0  1  0  0  1  0  1  1  ...   1   0   1   1   0   1   1   1   1   
15  0  0  0  1  1  0  1  1  1  1  ...   0   1   0   0   1   0   0   0   1   
9   0  0  1  0  0  0  1  0  0  1  ...   0   0   0   0   1   1   1   0   0   
8   0  0  1  1  1  0  1  0  0  1  ...   0   0   1   1   1   0   0   0   0   
11  0  0  1  1  1  1  0  1  0  0  ...   1   1   1   1   1   1   1   0   1   
2   0  0  1  1  1  1  1  0  1  1  ...   1   0   1   0   1   1   0   0   0   
0   0  1  0  0  0  1  0  0  0  1  ...   0   0   0   1   0   1   1   1   0   
13  0  1  0  0  0  1  1  1  0  0  ...   1   1   1   0   1   0   1   0   1   
10  0  1  0  0  1  0  1  1  1  0  ...   0   0   0   0   0   1   0   1   0   
17  0  1  0  1  0  0  0  1  1  0  ...   0   0   1   1   0   1   1   0   0   
4   0  1  0  1  0  0  1  0  1  1  ...   1   1   1   1   1   1   1   1   0   
27  0  1  0  1  0  1  0  1  1  0  ...   1   0   1   0   1   1   1   1   1   
22  0  1  0  1  1  0  0  1  0  1  ...   1   1   1   0   0   1   1   0   0   
5   0  1  1  1  1  1  1  1  1  0  ...   0   1   1   0   1   0   1   1   0   

    fitness  
3     28509  
25    77167  
15   114321  
9    140316  
8    239216  
11   250877  
2    257368  
0    279598  
13   291797  
10   309258  
17   334444  
4    339966  
27   350559  
22   366540  
5    522966  

[15 rows x 21 columns]

In [123]:
df = df.reset_index()
df

index  0  1  2  3  4  5  6  7  8  ...  11  12  13  14  15  16  17  18  19  \
0       3  0  0  0  0  0  1  1  0  1  ...   1   0   1   0   1   1   1   0   1   
1      25  0  0  0  1  0  0  1  0  1  ...   1   0   1   1   0   1   1   1   1   
2      15  0  0  0  1  1  0  1  1  1  ...   0   1   0   0   1   0   0   0   1   
3       9  0  0  1  0  0  0  1  0  0  ...   0   0   0   0   1   1   1   0   0   
4       8  0  0  1  1  1  0  1  0  0  ...   0   0   1   1   1   0   0   0   0   
5      11  0  0  1  1  1  1  0  1  0  ...   1   1   1   1   1   1   1   0   1   
6       2  0  0  1  1  1  1  1  0  1  ...   1   0   1   0   1   1   0   0   0   
7       0  0  1  0  0  0  1  0  0  0  ...   0   0   0   1   0   1   1   1   0   
8      13  0  1  0  0  0  1  1  1  0  ...   1   1   1   0   1   0   1   0   1   
9      10  0  1  0  0  1  0  1  1  1  ...   0   0   0   0   0   1   0   1   0   
10     17  0  1  0  1  0  0  0  1  1  ...   0   0   1   1   0   1   1   0   0   
11      4  0  1  0  1  0  0  1  0  1  ...   1   1   1   1   1   1   1   1   0   
12     27  0  1  0  1  0  1  0  1  1  ...   1   0   1   0   1   1   1   1   1   
13     22  0  1  0  1  1  0  0  1  0  ...   1   1   1   0   0   1   1   0   0   
14      5  0  1  1  1  1  1  1  1  1  ...   0   1   1   0   1   0   1   1   0   

    fitness  
0     28509  
1     77167  
2    114321  
3    140316  
4    239216  
5    250877  
6    257368  
7    279598  
8    291797  
9    309258  
10   334444  
11   339966  
12   350559  
13   366540  
14   522966  

[15 rows x 22 columns]

In [124]:
df = df.drop(['index'],axis=1)
df

0  1  2  3  4  5  6  7  8  9  ...  11  12  13  14  15  16  17  18  19  \
0   0  0  0  0  0  1  1  0  1  1  ...   1   0   1   0   1   1   1   0   1   
1   0  0  0  1  0  0  1  0  1  1  ...   1   0   1   1   0   1   1   1   1   
2   0  0  0  1  1  0  1  1  1  1  ...   0   1   0   0   1   0   0   0   1   
3   0  0  1  0  0  0  1  0  0  1  ...   0   0   0   0   1   1   1   0   0   
4   0  0  1  1  1  0  1  0  0  1  ...   0   0   1   1   1   0   0   0   0   
5   0  0  1  1  1  1  0  1  0  0  ...   1   1   1   1   1   1   1   0   1   
6   0  0  1  1  1  1  1  0  1  1  ...   1   0   1   0   1   1   0   0   0   
7   0  1  0  0  0  1  0  0  0  1  ...   0   0   0   1   0   1   1   1   0   
8   0  1  0  0  0  1  1  1  0  0  ...   1   1   1   0   1   0   1   0   1   
9   0  1  0  0  1  0  1  1  1  0  ...   0   0   0   0   0   1   0   1   0   
10  0  1  0  1  0  0  0  1  1  0  ...   0   0   1   1   0   1   1   0   0   
11  0  1  0  1  0  0  1  0  1  1  ...   1   1   1   1   1   1   1   1   0   
12  0  1  0  1  0  1  0  1  1  0  ...   1   0   1   0   1   1   1   1   1   
13  0  1  0  1  1  0  0  1  0  1  ...   1   1   1   0   0   1   1   0   0   
14  0  1  1  1  1  1  1  1  1  0  ...   0   1   1   0   1   0   1   1   0   

    fitness  
0     28509  
1     77167  
2    114321  
3    140316  
4    239216  
5    250877  
6    257368  
7    279598  
8    291797  
9    309258  
10   334444  
11   339966  
12   350559  
13   366540  
14   522966  

[15 rows x 21 columns]

In [125]:
df = df.drop(['fitness'],axis=1)
df

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19
0   0  0  0  0  0  1  1  0  1  1   1   1   0   1   0   1   1   1   0   1
1   0  0  0  1  0  0  1  0  1  1   0   1   0   1   1   0   1   1   1   1
2   0  0  0  1  1  0  1  1  1  1   1   0   1   0   0   1   0   0   0   1
3   0  0  1  0  0  0  1  0  0  1   0   0   0   0   0   1   1   1   0   0
4   0  0  1  1  1  0  1  0  0  1   1   0   0   1   1   1   0   0   0   0
5   0  0  1  1  1  1  0  1  0  0   1   1   1   1   1   1   1   1   0   1
6   0  0  1  1  1  1  1  0  1  1   0   1   0   1   0   1   1   0   0   0
7   0  1  0  0  0  1  0  0  0  1   0   0   0   0   1   0   1   1   1   0
8   0  1  0  0  0  1  1  1  0  0   1   1   1   1   0   1   0   1   0   1
9   0  1  0  0  1  0  1  1  1  0   0   0   0   0   0   0   1   0   1   0
10  0  1  0  1  0  0  0  1  1  0   1   0   0   1   1   0   1   1   0   0
11  0  1  0  1  0  0  1  0  1  1   1   1   1   1   1   1   1   1   1   0
12  0  1  0  1  0  1  0  1  1  0   0   1   0   1   0   1   1   1   1   1
13  0  1  0  1  1  0  0  1  0  1   1   1   1   1   0   0   1   1   0   0
14  0  1  1  1  1  1  1  1  1  0   1   0   1   1   0   1   0   1   1   0

In [126]:
df

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19
0   0  0  0  0  0  1  1  0  1  1   1   1   0   1   0   1   1   1   0   1
1   0  0  0  1  0  0  1  0  1  1   0   1   0   1   1   0   1   1   1   1
2   0  0  0  1  1  0  1  1  1  1   1   0   1   0   0   1   0   0   0   1
3   0  0  1  0  0  0  1  0  0  1   0   0   0   0   0   1   1   1   0   0
4   0  0  1  1  1  0  1  0  0  1   1   0   0   1   1   1   0   0   0   0
5   0  0  1  1  1  1  0  1  0  0   1   1   1   1   1   1   1   1   0   1
6   0  0  1  1  1  1  1  0  1  1   0   1   0   1   0   1   1   0   0   0
7   0  1  0  0  0  1  0  0  0  1   0   0   0   0   1   0   1   1   1   0
8   0  1  0  0  0  1  1  1  0  0   1   1   1   1   0   1   0   1   0   1
9   0  1  0  0  1  0  1  1  1  0   0   0   0   0   0   0   1   0   1   0
10  0  1  0  1  0  0  0  1  1  0   1   0   0   1   1   0   1   1   0   0
11  0  1  0  1  0  0  1  0  1  1   1   1   1   1   1   1   1   1   1   0
12  0  1  0  1  0  1  0  1  1  0   0   1   0   1   0   1   1   1   1   1
13  0  1  0  1  1  0  0  1  0  1   1   1   1   1   0   0   1   1   0   0
14  0  1  1  1  1  1  1  1  1  0   1   0   1   1   0   1   0   1   1   0

In [127]:
l1 = list(df.iloc[0])
l2 = list(df.iloc[1])
print(l1)
print(l2)

[0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1]
[0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1]


In [128]:
l = l1[:5] + l2[5:]
l

[0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1]

In [129]:
l[10] = 1 - l[10]
l[10]

1

In [130]:
count = 0
new_child = list()
for i in range(1):
    list1 = list(df.iloc[i])
    for j in range(1,len(df)):
        list2 = list(df.iloc[j])
        l = list1[:5] + list2[5:]
        l[10] = 1 - l[10]
        new_child.append(l)
new_child

[[0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1],
 [0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0],
 [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0]]

In [131]:
len(new_child)

14

In [132]:
df = pd.DataFrame(data=new_child)
df

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  \
0    0   0   0   0   0   0   1   0   1   1   1   1   0   1   1   0   1   1   
1    0   0   0   0   0   0   1   1   1   1   0   0   1   0   0   1   0   0   
2    0   0   0   0   0   0   1   0   0   1   1   0   0   0   0   1   1   1   
3    0   0   0   0   0   0   1   0   0   1   0   0   0   1   1   1   0   0   
4    0   0   0   0   0   1   0   1   0   0   0   1   1   1   1   1   1   1   
5    0   0   0   0   0   1   1   0   1   1   1   1   0   1   0   1   1   0   
6    0   0   0   0   0   1   0   0   0   1   1   0   0   0   1   0   1   1   
7    0   0   0   0   0   1   1   1   0   0   0   1   1   1   0   1   0   1   
8    0   0   0   0   0   0   1   1   1   0   1   0   0   0   0   0   1   0   
9    0   0   0   0   0   0   0   1   1   0   0   0   0   1   1   0   1   1   
10   0   0   0   0   0   0   1   0   1   1   0   1   1   1   1   1   1   1   
11   0   0   0   0   0   1   0   1   1   0   1   1   0   1   0   1   1   1   
12   0   0   0   0   0   0   0   1   0   1   0   1   1   1   0   0   1   1   
13   0   0   0   0   0   1   1   1   1   0   0   0   1   1   0   1   0   1   

    18  19  
0    1   1  
1    0   1  
2    0   0  
3    0   0  
4    0   1  
5    0   0  
6    1   0  
7    0   1  
8    1   0  
9    0   0  
10   1   0  
11   1   1  
12   0   0  
13   1   0