# Single Perceptron for n bit data


## Library

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
import math 

## Dataset

In [2]:
df = pd.read_excel('Cryotherapy.xlsx')
df

sex  age   Time  Number_of_Warts  Type  Area  Result_of_Treatment
0     1   35  12.00                5     1   100                    0
1     1   29   7.00                5     1    96                    1
2     1   50   8.00                1     3   132                    0
3     1   32  11.75                7     3   750                    0
4     1   67   9.25                1     1    42                    0
..  ...  ...    ...              ...   ...   ...                  ...
85    2   34  12.00                3     3    95                    0
86    2   20   3.50                6     1    75                    1
87    2   35   8.25                8     3   100                    0
88    1   24  10.75               10     1    20                    1
89    1   19   8.00                8     1   160                    1

[90 rows x 7 columns]

In [3]:
output = df['Result_of_Treatment']
output

0     0
1     1
2     0
3     0
4     0
     ..
85    0
86    1
87    0
88    1
89    1
Name: Result_of_Treatment, Length: 90, dtype: int64

In [4]:
df['Result_of_Treatment'].value_counts()

1    48
0    42
Name: Result_of_Treatment, dtype: int64

In [5]:
df = df.drop('Result_of_Treatment',axis=1)
df

sex  age   Time  Number_of_Warts  Type  Area
0     1   35  12.00                5     1   100
1     1   29   7.00                5     1    96
2     1   50   8.00                1     3   132
3     1   32  11.75                7     3   750
4     1   67   9.25                1     1    42
..  ...  ...    ...              ...   ...   ...
85    2   34  12.00                3     3    95
86    2   20   3.50                6     1    75
87    2   35   8.25                8     3   100
88    1   24  10.75               10     1    20
89    1   19   8.00                8     1   160

[90 rows x 6 columns]

In [6]:
# number of features or columns
n = len(df.columns)
total_number = len(df) 

## Train Test Split

In [7]:
train_percentage = 70
test_percentage = 100 - train_percentage

print('Train Percentage :',train_percentage)
print('Test Percentage :',test_percentage)

Train Percentage : 70
Test Percentage : 30


In [8]:
import math

no_of_train_data = math.ceil(( total_number * train_percentage ) / 100)
no_of_test_data = total_number - no_of_train_data

print('No of Train Data :',no_of_train_data)
print('No of Test Data :',no_of_test_data)

No of Train Data : 63
No of Test Data : 27


## Inititalizing Wij , bj , Wjk and bk with random values

In [9]:
# n is the number of nodes in input layer and hidden layer
# m is the number of nodes in output layer

unique = dict()

for i in output:
    if i not in unique:
        unique[i] = 1
    else:
        unique[i] = unique[i] + 1

print('Total Class in Output :',len(unique))

Total Class in Output : 2


In [10]:
import numpy as np
import math

# n will be as it is
m = math.ceil(np.log2(len(unique)))

print('Number of nodes in input layer :',n)
print('Number of nodes in hidden layer :',n)
print('Number of nodes in output layer :',m)

Number of nodes in input layer : 6
Number of nodes in hidden layer : 6
Number of nodes in output layer : 1


In [11]:
np.random.seed(113)
Wij = np.random.rand(n,n)
bj = np.random.rand(n)
Wjk = np.random.rand(n,m)
bk = np.random.rand(m)

In [12]:
print('Weights from i to j :\n',Wij)
print('\nBias to j :\n',bj)
print('\nWeights from j to k :\n',Wjk)
print('\nBias to k :\n',bk)

Weights from i to j :
 [[0.85198549 0.0739036  0.89493176 0.43649355 0.12767773 0.57585787]
 [0.84047092 0.43512055 0.69591056 0.6846381  0.70064837 0.77969426]
 [0.64274937 0.96102617 0.10846489 0.79610634 0.83258008 0.26600836]
 [0.83668539 0.53212691 0.51690756 0.09858771 0.91886899 0.66665849]
 [0.17477948 0.21769151 0.46787528 0.43589124 0.88935448 0.22259927]
 [0.58901937 0.27720157 0.52572218 0.25935711 0.52894863 0.31214075]]

Bias to j :
 [0.54416225 0.2420565  0.09423802 0.18946638 0.15028533 0.89444684]

Weights from j to k :
 [[0.3007521 ]
 [0.27286447]
 [0.00647975]
 [0.59801345]
 [0.79435088]
 [0.59862107]]

Bias to k :
 [0.61498669]


In [13]:
Wij[0,0]

0.8519854927300882

## Initializing Oi , netj , Oj and netk with 0

In [14]:
Oi = np.zeros(n)

netj = np.zeros(n)
activj = np.zeros(n)
Oj = np.zeros(n)

netk = np.zeros(m)
activk = np.zeros(m)
Ok = np.zeros(m)

In [15]:
# learning rate
learning_rate = 0.5

## initializing delta_Wjk , delta_bk , delta_Wij , delta_bj with 0

In [16]:
delta_Wjk = np.zeros((n,m))
delta_bk = np.zeros(m)
delta_Wij = np.zeros((n,n))
delta_bj = np.zeros(n)

## Forward Propagation and Backward Propagation

In [17]:
df

sex  age   Time  Number_of_Warts  Type  Area
0     1   35  12.00                5     1   100
1     1   29   7.00                5     1    96
2     1   50   8.00                1     3   132
3     1   32  11.75                7     3   750
4     1   67   9.25                1     1    42
..  ...  ...    ...              ...   ...   ...
85    2   34  12.00                3     3    95
86    2   20   3.50                6     1    75
87    2   35   8.25                8     3   100
88    1   24  10.75               10     1    20
89    1   19   8.00                8     1   160

[90 rows x 6 columns]

In [18]:
output

0     0
1     1
2     0
3     0
4     0
     ..
85    0
86    1
87    0
88    1
89    1
Name: Result_of_Treatment, Length: 90, dtype: int64

In [19]:
df[df.columns[0]][4]

1

In [20]:
np.exp(1)

2.718281828459045

In [21]:
n

6

In [27]:
l = list()
count = 0
while count != no_of_train_data :
    for row in range(no_of_train_data):
        # forward propagation starts

        for column in range(len(df.columns)):
            Oi[column] = df[df.columns[column]][row]
            
        for i in range(n):
            for j in range(n):
                netj[j] = netj[j] + Oi[i] * Wij[i,j]
        
        
        for j in range(n):
            activj[j] = netj[j] + bj[j]
        
        for j in range(n):
            Oj[j] = 1 / (1 + np.exp(-1*activj[j]))

        for j in range(n):
            for k in range(m):
                netk[k] = netk[k] + Oj[j] * Wjk[j,k]

        for k in range(m):
            activk[k] = netk[k] + bk[k]
        
        for k in range(m):
            Ok[k] = 1 / (1 + np.exp(-1*activk[k]))
        
        delta = output[row] - Ok[0] # not generalized
        error = 0.5 * ( delta ** 2)
        if error <= 0.01:
            l.append(Ok[0])
            count = count + 1
            netj = np.zeros(n)
            netk = np.zeros(m)
            continue
        
        
        # Backpropagation starts

        for j in range(n):
            for k in range(m):
                delta_Wjk[j,k] = learning_rate * delta * Oj[j] * Ok[k] * (1 - Ok[k])
        
        for j in range(n):
            for k in range(m):
                Wjk[j,k] = Wjk[j,k] + delta_Wjk[j,k]

        for k in range(m):
            delta_bk[k] = learning_rate * delta * Ok[k] * (1 - Ok[k])

        for k in range(m):
            bk[k] = bk[k] + delta_bk[k]
        
        summation = 0
        for j in range(n):
            summation = summation + Wjk[j,0] * delta

        for i in range(n):
            for j in range(n):
                delta_Wij[i,j] = learning_rate * Oi[i] * Oj[j] * (1-Oj[j]) * summation

        for i in range(n):
            for j in range(n):
                Wij[i,j] = Wij[i,j] + delta_Wij[i,j]

        for j in range(n):
            delta_bj[j] = learning_rate * Oj[j] * (1 - Oj[j]) * summation

        for j in range(n):
            bj[j] = bj[j] + delta_bj[j] 

        netj = np.zeros(n)
        netk = np.zeros(m)
        count = 0
        l = list()
        break      

In [28]:
count

12

In [29]:
l

[0.13859371326555509,
 0.11784658969017542,
 0.11219060090480577,
 0.10104441873376377,
 0.11652501315300999,
 0.1035533740319198,
 0.10041976198227501,
 0.09333438950480245,
 0.8752301770087584,
 0.8704865786654388,
 0.8685175024285732,
 0.8600370620460503]

In [30]:
right = 0
wrong = 0
l = list()
for row in range(no_of_train_data,total_number):
    # forward propagation starts

    for column in range(len(df.columns)):
        Oi[column] = df[df.columns[column]][row]
        
    for i in range(n):
        for j in range(n):
            netj[j] = netj[j] + Oi[i] * Wij[i,j]
    
    
    for j in range(n):
        activj[j] = netj[j] + bj[j]
    
    for j in range(n):
        Oj[j] = 1 / (1 + np.exp(-1*activj[j]))

    for j in range(n):
        for k in range(m):
            netk[k] = netk[k] + Oj[j] * Wjk[j,k]

    for k in range(m):
        activk[k] = netk[k] + bk[k]
    
    for k in range(m):
        Ok[k] = 1 / (1 + np.exp(-1*activk[k]))
    
    delta = output[row] - Ok[0] # not generalized
    error = 0.5 * ( delta ** 2)
    l.append(error)

    if error <= 0.01:
        right = right + 1
    else:
        wrong = wrong + 1
    
accuracy = ( right * 100 ) / no_of_test_data

print(l)
print("No of Test Data :",no_of_test_data)
print("Right :",right)
print("Wrong :",wrong)
print("Accuracy :",accuracy)

[0.008513240886662185, 0.008528250789842408, 0.008528389396514395, 0.008528391294174587]
No of Test Data : 4
Right : 4
Wrong : 0
Accuracy : 100.0
