# Single Perceptron for n bit data


## Generating n bit of data

In [1]:
n = int(input('Enter Number of bits : '))
count = 0
i = n
string = 'bit_'
total_number = 2 ** n

In [2]:
value = list()
dictionary = dict()

while i >= 1 :
    key = string + str(i)
    d = 2 ** count

    while len(value) != total_number:
        for j in range(d):
            value.append(0)
        for j in range(d):
            value.append(1)
    
    dictionary[key] = value
    value = list()
    count = count + 1
    i = i - 1

In [3]:
dictionary 

{'bit_3': [0, 1, 0, 1, 0, 1, 0, 1],
 'bit_2': [0, 0, 1, 1, 0, 0, 1, 1],
 'bit_1': [0, 0, 0, 0, 1, 1, 1, 1]}

In [4]:
list(dictionary.items())

[('bit_3', [0, 1, 0, 1, 0, 1, 0, 1]),
 ('bit_2', [0, 0, 1, 1, 0, 0, 1, 1]),
 ('bit_1', [0, 0, 0, 0, 1, 1, 1, 1])]

In [5]:
l = list(dictionary.items())
l

[('bit_3', [0, 1, 0, 1, 0, 1, 0, 1]),
 ('bit_2', [0, 0, 1, 1, 0, 0, 1, 1]),
 ('bit_1', [0, 0, 0, 0, 1, 1, 1, 1])]

In [6]:
reversed_dictionary = dict()
i = n-1
while i >= 0:
    reversed_dictionary[l[i][0]] = l[i][1]
    i = i - 1
reversed_dictionary

{'bit_1': [0, 0, 0, 0, 1, 1, 1, 1],
 'bit_2': [0, 0, 1, 1, 0, 0, 1, 1],
 'bit_3': [0, 1, 0, 1, 0, 1, 0, 1]}

In [7]:
dictionary = reversed_dictionary
dictionary

{'bit_1': [0, 0, 0, 0, 1, 1, 1, 1],
 'bit_2': [0, 0, 1, 1, 0, 0, 1, 1],
 'bit_3': [0, 1, 0, 1, 0, 1, 0, 1]}

In [8]:
output = dictionary['bit_1']
output

[0, 0, 0, 0, 1, 1, 1, 1]

In [9]:
import pandas as pd

df = pd.DataFrame(data=dictionary)
df

bit_1  bit_2  bit_3
0      0      0      0
1      0      0      1
2      0      1      0
3      0      1      1
4      1      0      0
5      1      0      1
6      1      1      0
7      1      1      1

In [10]:
df['Output'] = output
df

bit_1  bit_2  bit_3  Output
0      0      0      0       0
1      0      0      1       0
2      0      1      0       0
3      0      1      1       0
4      1      0      0       1
5      1      0      1       1
6      1      1      0       1
7      1      1      1       1

In [11]:
df = df.drop('Output',axis=1)
df

bit_1  bit_2  bit_3
0      0      0      0
1      0      0      1
2      0      1      0
3      0      1      1
4      1      0      0
5      1      0      1
6      1      1      0
7      1      1      1

## Inititalizing Wij , bj , Wjk and bk with random values

In [12]:
# n is the number of nodes in input layer and hidden layer
# m is the number of nodes in output layer

unique = dict()

for i in output:
    if i not in unique:
        unique[i] = 1
    else:
        unique[i] = unique[i] + 1

print('Total Class in Output :',len(unique))

Total Class in Output : 2


In [13]:
import numpy as np
import math

# n will be as it is
m = math.ceil(np.log2(len(unique)))

print('Number of nodes in input layer :',n)
print('Number of nodes in hidden layer :',n)
print('Number of nodes in output layer :',m)

Number of nodes in input layer : 3
Number of nodes in hidden layer : 3
Number of nodes in output layer : 1


In [14]:
np.random.seed(113)
Wij = np.random.rand(n,n)
bj = np.random.rand(n)
Wjk = np.random.rand(n,m)
bk = np.random.rand(m)

In [15]:
print('Weights from i to j :\n',Wij)
print('\nBias to j :\n',bj)
print('\nWeights from j to k :\n',Wjk)
print('\nBias to k :\n',bk)

Weights from i to j :
 [[0.85198549 0.0739036  0.89493176]
 [0.43649355 0.12767773 0.57585787]
 [0.84047092 0.43512055 0.69591056]]

Bias to j :
 [0.6846381  0.70064837 0.77969426]

Weights from j to k :
 [[0.64274937]
 [0.96102617]
 [0.10846489]]

Bias to k :
 [0.79610634]


In [16]:
Wij[0,0]

0.8519854927300882

## Initializing Oi , netj , Oj and netk with 0

In [17]:
Oi = np.zeros(n)

netj = np.zeros(n)
activj = np.zeros(n)
Oj = np.zeros(n)

netk = np.zeros(m)
activk = np.zeros(m)
Ok = np.zeros(m)

In [18]:
# learning rate
learning_rate = 0.5

## initializing delta_Wjk , delta_bk , delta_Wij , delta_bj with 0

In [19]:
delta_Wjk = np.zeros((n,m))
delta_bk = np.zeros(m)
delta_Wij = np.zeros((n,n))
delta_bj = np.zeros(n)

## Forward Propagation and Backward Propagation

In [20]:
df

bit_1  bit_2  bit_3
0      0      0      0
1      0      0      1
2      0      1      0
3      0      1      1
4      1      0      0
5      1      0      1
6      1      1      0
7      1      1      1

In [21]:
output

[0, 0, 0, 0, 1, 1, 1, 1]

In [22]:
df[df.columns[0]][4]

1

In [23]:
np.exp(1)

2.718281828459045

In [24]:
n

3

In [25]:
l = list()
count = 0
while count != len(df) :
    for row in range(len(df)):
        # forward propagation starts

        for column in range(len(df.columns)):
            Oi[column] = df[df.columns[column]][row]
            
        for i in range(n):
            for j in range(n):
                netj[j] = netj[j] + Oi[i] * Wij[i,j]
        
        
        for j in range(n):
            activj[j] = netj[j] + bj[j]
        
        for j in range(n):
            Oj[j] = 1 / (1 + np.exp(-1*activj[j]))

        for j in range(n):
            for k in range(m):
                netk[k] = netk[k] + Oj[j] * Wjk[j,k]

        for k in range(m):
            activk[k] = netk[k] + bk[k]
        
        for k in range(m):
            Ok[k] = 1 / (1 + np.exp(-1*activk[k]))
        
        delta = output[row] - Ok[0] # not generalized
        error = 0.5 * ( delta ** 2)
        if error <= 0.01:
            l.append(Ok[0])
            count = count + 1
            netj = np.zeros(n)
            netk = np.zeros(m)
            continue
        
        
        # Backpropagation starts

        for j in range(n):
            for k in range(m):
                delta_Wjk[j,k] = learning_rate * delta * Oj[j] * Ok[k] * (1 - Ok[k])
        
        for j in range(n):
            for k in range(m):
                Wjk[j,k] = Wjk[j,k] + delta_Wjk[j,k]

        for k in range(m):
            delta_bk[k] = learning_rate * delta * Ok[k] * (1 - Ok[k])

        for k in range(m):
            bk[k] = bk[k] + delta_bk[k]
        
        summation = 0
        for j in range(n):
            summation = summation + Wjk[j,0] * delta

        for i in range(n):
            for j in range(n):
                delta_Wij[i,j] = learning_rate * Oi[i] * Oj[j] * (1-Oj[j]) * summation

        for i in range(n):
            for j in range(n):
                Wij[i,j] = Wij[i,j] + delta_Wij[i,j]

        for j in range(n):
            delta_bj[j] = learning_rate * Oj[j] * (1 - Oj[j]) * summation

        for j in range(n):
            bj[j] = bj[j] + delta_bj[j] 

        netj = np.zeros(n)
        netk = np.zeros(m)
        count = 0
        l = list()
        break      

In [26]:
count

8

In [27]:
l

[0.13835176534756652,
 0.11983764710251497,
 0.12434394710668853,
 0.11162535087765253,
 0.8714961785987091,
 0.8658886138379354,
 0.8676767605762661,
 0.8594704058473127]